theme = "catppuccin_mocha"

[editor]
color-modes = true
cursorline = true
line-number = "relative"
mouse = false
rulers = [80]
bufferline = "multiple"

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
C-r = [":config-reload", ":reload"]
ret = ":w"
T = ["goto_first_nonwhitespace", 'find_till_char'] # ..??, change_selection]
space = { c = ":bc" }
X = "extend_line_above"
H = ":buffer-previous"
L = ":buffer-next"
D = ":buffer-close-others"
d = ["yank_main_selection_to_clipboard", "normal_mode", "delete_selection"]
# y = ["yank",":clipboard-yank"]
# p = ["paste_after",":clipboard-paste-after"]
# P = ["paste_before",":clipboard-paste-before"]

[keys.insert]
down = "move_line_down"
up = "move_line_up"
left = "move_char_left"
right = "move_char_right"

[editor.lsp]
display-messages = false
snippets = true
auto-signature-help = false
display-signature-help-docs = false

[editor.file-picker]
git-ignore = true
hidden = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.statusline]
center = ["file-name"]
left = ["mode", "spinner"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
